"""Shared pytest fixtures for backend tests."""

from pathlib import Path

import pytest

from backend.app.config import get_settings

CONVOINTEL_ENV_VARS = (
    "CONVOINTEL_ENV",
    "CONVOINTEL_HOST",
    "CONVOINTEL_PORT",
    "CONVOINTEL_LOG_LEVEL",
    "CONVOINTEL_DATA_DIR",
    "OPENAI_API_KEY",
    "CONVOINTEL_OPENAI_API_KEY",
    "CONVOINTEL_TRANSCRIPTION_MODEL",
    "CONVOINTEL_TRANSCRIPTION_TIMEOUT_SECONDS",
    "CONVOINTEL_TRANSCRIPTION_MAX_RETRIES",
    "CONVOINTEL_TRANSCRIPTION_LANGUAGE",
    "CONVOINTEL_CLEANUP_MODEL",
    "CONVOINTEL_CLEANUP_TIMEOUT_SECONDS",
    "CONVOINTEL_CLEANUP_MAX_RETRIES",
    "CONVOINTEL_CLEANUP_MAX_BATCH_CHARACTERS",
    "CONVOINTEL_CLEANUP_MAX_OUTPUT_TOKENS",
    "CONVOINTEL_INTELLIGENCE_MODEL",
    "CONVOINTEL_INTELLIGENCE_TIMEOUT_SECONDS",
    "CONVOINTEL_INTELLIGENCE_MAX_RETRIES",
    "CONVOINTEL_INTELLIGENCE_MAX_INPUT_CHARACTERS",
    "CONVOINTEL_INTELLIGENCE_MAX_OUTPUT_TOKENS",
    "CONVOINTEL_INTELLIGENCE_MAX_ITEMS_PER_CATEGORY",
    "CONVOINTEL_TEMPORAL_MODEL",
    "CONVOINTEL_TEMPORAL_TIMEOUT_SECONDS",
    "CONVOINTEL_TEMPORAL_MAX_RETRIES",
    "CONVOINTEL_TEMPORAL_MAX_INPUT_CHARACTERS",
    "CONVOINTEL_TEMPORAL_MAX_OUTPUT_TOKENS",
    "CONVOINTEL_TEMPORAL_MAX_ITEMS",
    "CONVOINTEL_GOOGLE_CALENDAR_CLIENT_SECRET_PATH",
    "CONVOINTEL_GOOGLE_CALENDAR_TOKEN_PATH",
    "CONVOINTEL_GOOGLE_CALENDAR_ID",
)


def pytest_configure(config: pytest.Config) -> None:
    """Ensure the repository-local generated pytest artifact parent exists."""

    Path(config.rootpath, ".test-artifacts").mkdir(exist_ok=True)


@pytest.fixture(autouse=True)
def isolate_settings(monkeypatch: pytest.MonkeyPatch):
    for env_var in CONVOINTEL_ENV_VARS:
        monkeypatch.delenv(env_var, raising=False)
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()
